var e = "https://daxichong.com/daxichong/addons/zjhj_mall/core/web/debug.php?store_id=4&r=api/",
  r = {
    index: e + "default/index",
    default: {
      store: e + "default/store",
      index: e + "default/index",
      goods_list: e + "default/goods-list",
      cat_list: e + "default/cat-list",
      goods: e + "default/goods",
      district: e + "default/district",
      goods_attr_info: e + "default/goods-attr-info",
      upload_image: e + "default/upload-image",
      comment_list: e + "default/comment-list",
      article_list: e + "default/article-list",
      article_detail: e + "default/article-detail",
      video_list: e + "default/video-list",
      goods_qrcode: e + "default/goods-qrcode",
      coupon_list: e + "default/coupon-list",
      topic_list: e + "default/topic-list",
      topic: e + "default/topic",
      navbar: e + "default/navbar",
      navigation_bar_color: e + "default/navigation-bar-color",
      shop_list: e + "default/shop-list",
      shop_detail: e + "default/shop-detail",
      topic_type: e + "default/topic-type",
      buy_data: e + "default/buy-data",
      goods_recommend: e + "default/goods-recommend",
      search: e + "default/search",
      cats: e + "default/cats"
    },
    cart: {
      list: e + "cart/list",
      add_cart: e + "cart/add-cart",
      delete: e + "cart/delete",
      cart_edit: e + "cart/cart-edit"
    },
    passport: {
      login: e + "passport/login",
      on_login: e + "passport/on-login"
    },
    order: {
      submit_preview: e + "order/submit-preview",
      submit: e + "order/submit",
      pay_data: e + "order/pay-data",
      list: e + "order/list",
      revoke: e + "order/revoke",
      confirm: e + "order/confirm",
      count_data: e + "order/count-data",
      detail: e + "order/detail",
      refund_preview: e + "order/refund-preview",
      refund: e + "order/refund",
      refund_detail: e + "order/refund-detail",
      comment_preview: e + "order/comment-preview",
      comment: e + "order/comment",
      express_detail: e + "order/express-detail",
      clerk: e + "order/clerk",
      clerk_detail: e + "order/clerk-detail",
      get_qrcode: e + "order/get-qrcode",
      location: e + "order/location",
      refund_send: e + "order/refund-send"
    },
    user: {
      address_list: e + "user/address-list",
      address_detail: e + "user/address-detail",
      address_save: e + "user/address-save",
      address_set_default: e + "user/address-set-default",
      address_delete: e + "user/address-delete",
      save_form_id: e + "user/save-form-id",
      favorite_add: e + "user/favorite-add",
      favorite_remove: e + "user/favorite-remove",
      favorite_list: e + "user/favorite-list",
      index: e + "user/index",
      wechat_district: e + "user/wechat-district",
      add_wechat_address: e + "user/add-wechat-address",
      topic_favorite: e + "user/topic-favorite",
      topic_favorite_list: e + "user/topic-favorite-list",
      member: e + "user/member",
      card: e + "user/card",
      card_qrcode: e + "user/card-qrcode",
      card_clerk: e + "user/card-clerk",
      web_login: e + "user/web-login",
      submit_member: e + "user/submit-member",
      user_binding: e + "user/user-binding",
      user_hand_binding: e + "user/user-hand-binding",
      user_empower: e + "user/user-empower",
      sms_setting: e + "user/sms-setting",
      authorization_bind: e + "user/authorization-bind",
      check_bind: e + "user/check-bind"
    },
    share: {
      join: e + "share/join",
      check: e + "share/check",
      get_info: e + "share/get-info",
      get_price: e + "share/get-price",
      apply: e + "share/apply",
      cash_detail: e + "share/cash-detail",
      get_qrcode: e + "share/get-qrcode",
      shop_share: e + "share/shop-share",
      bind_parent: e + "share/bind-parent",
      get_team: e + "share/get-team",
      get_order: e + "share/get-order",
      index: e + "share/index"
    },
    coupon: {
      index: e + "coupon/index",
      share_send: e + "coupon/share-send",
      receive: e + "coupon/receive"
    },
    miaosha: {
      list: e + "miaosha/list",
      goods_list: e + "miaosha/goods-list",
      details: e + "miaosha/details",
      submit_preview: e + "miaosha/submit-preview",
      submit: e + "miaosha/submit",
      pay_data: e + "miaosha/pay-data",
      order_list: e + "miaosha/order-list",
      order_details: e + "miaosha/order-details",
      order_revoke: e + "miaosha/revoke",
      express_detail: e + "miaosha/express-detail",
      confirm: e + "miaosha/confirm",
      comment_preview: e + "miaosha/comment-preview",
      comment: e + "miaosha/comment",
      refund_preview: e + "miaosha/refund-preview",
      refund: e + "miaosha/refund",
      refund_detail: e + "miaosha/refund-detail",
      comment_list: e + "miaosha/comment-list",
      goods_qrcode: e + "miaosha/goods-qrcode"
    },
    group: {
      index: e + "group/index/index",
      list: e + "group/index/good-list",
      details: e + "group/index/good-details",
      goods_attr_info: e + "group/index/goods-attr-info",
      submit_preview: e + "group/order/submit-preview",
      submit: e + "group/order/submit",
      pay_data: e + "group/order/pay-data",
      order: {
        list: e + "group/order/list",
        detail: e + "group/order/detail",
        express_detail: e + "group/order/express-detail",
        comment_preview: e + "group/order/comment-preview",
        comment: e + "group/order/comment",
        confirm: e + "group/order/confirm",
        goods_qrcode: e + "group/order/goods-qrcode",
        get_qrcode: e + "group/order/get-qrcode",
        clerk: e + "group/order/clerk",
        clerk_order_details: e + "group/order/clerk-order-details",
        revoke: e + "group/order/revoke",
        refund_preview: e + "group/order/refund-preview",
        refund: e + "group/order/refund",
        refund_detail: e + "group/order/refund-detail"
      },
      group_info: e + "group/order/group",
      comment: e + "group/index/goods-comment",
      goods_qrcode: e + "group/index/goods-qrcode",
      search: e + "group/index/search"
    },
    book: {
      index: e + "book/index/index",
      list: e + "book/index/good-list",
      details: e + "book/index/good-details",
      submit_preview: e + "book/order/submit-preview",
      submit: e + "book/order/submit",
      order_list: e + "book/order/list",
      order_cancel: e + "book/order/cancel",
      order_pay: e + "book/order/pay-data",
      order_details: e + "book/order/order-details",
      shop_list: e + "book/index/shop-list",
      get_qrcode: e + "book/order/get-qrcode",
      clerk: e + "book/order/clerk",
      apply_refund: e + "book/order/apply-refund",
      comment_preview: e + "book/order/comment-preview",
      submit_comment: e + "book/order/comment",
      goods_comment: e + "book/index/goods-comment",
      goods_qrcode: e + "book/index/goods-qrcode",
      clerk_order_details: e + "book/order/clerk-order-details"
    },
    quick: {
      quick: e + "quick/quick/quick",
      quick_goods: e + "quick/quick/quick-goods",
      quick_car: e + "quick/quick/quick-car"
    },
    fxhb: {
      open: e + "fxhb/index/open",
      open_submit: e + "fxhb/index/open-submit",
      detail: e + "fxhb/index/detail",
      detail_submit: e + "fxhb/index/detail-submit"
    },
    recharge: {
      index: e + "recharge/index",
      list: e + "recharge/list",
      submit: e + "recharge/submit",
      record: e + "recharge/record",
      detail: e + "recharge/detail"
    },
    mch: {
      apply: e + "mch/index/apply",
      apply_submit: e + "mch/index/apply-submit",
      shop: e + "mch/index/shop",
      shop_list: e + "mch/index/shop-list",
      shop_cat: e + "mch/index/shop-cat",
      user: {
        myshop: e + "mch/user/myshop",
        setting: e + "mch/user/setting",
        setting_submit: e + "mch/user/setting-submit",
        shop_qrcode: e + "mch/user/shop-qrcode",
        account: e + "mch/user/account",
        cash: e + "mch/user/cash",
        account_log: e + "mch/user/account-log",
        cash_log: e + "mch/user/cash-log",
        tongji_year_list: e + "mch/user/tongji-year-list",
        tongji_month_data: e + "mch/user/tongji-month-data",
        cash_preview: e + "mch/user/cash-preview"
      },
      goods: {
        list: e + "mch/goods/list",
        set_status: e + "mch/goods/set-status",
        delete: e + "mch/goods/delete"
      },
      order: {
        list: e + "mch/order/list",
        detail: e + "mch/order/detail",
        send: e + "mch/order/send",
        refund: e + "mch/order/refund",
        edit_price: e + "mch/order/edit-price",
        refund_detail: e + "mch/order/refund-detail"
      }
    },
    integral: {
      index: e + "integralmall/integralmall/index",
      coupon_info: e + "integralmall/integralmall/coupon-info",
      exchange_coupon: e + "integralmall/integralmall/exchange-coupon",
      integral_pay: e + "integralmall/integralmall/integral-pay",
      goods_info: e + "integralmall/integralmall/goods-info",
      submit_preview: e + "integralmall/integralmall/submit-preview",
      submit: e + "integralmall/integralmall/submit",
      list: e + "integralmall/integralmall/list",
      revoke: e + "integralmall/integralmall/revoke",
      order_submit: e + "integralmall/integralmall/order-submit",
      confirm: e + "integralmall/integralmall/confirm",
      get_qrcode: e + "integralmall/integralmall/get-qrcode",
      clerk_order_details: e + "integralmall/integralmall/clerk-order-details",
      clerk: e + "integralmall/integralmall/clerk",
      explain: e + "integralmall/integralmall/explain",
      exchange: e + "integralmall/integralmall/exchange",
      register: e + "integralmall/integralmall/register",
      integral_detail: e + "integralmall/integralmall/integral-detail"
    },
    pond: {
      index: e + "pond/pond/index",
      lottery: e + "pond/pond/lottery",
      prize: e + "pond/pond/prize",
      send: e + "pond/pond/send",
      setting: e + "pond/pond/setting",
      submit: e + "pond/pond/submit",
      qrcode: e + "pond/pond/qrcode"
    },
    scratch: {
      index: e + "scratch/scratch/index",
      receive: e + "scratch/scratch/receive",
      setting: e + "scratch/scratch/setting",
      prize: e + "scratch/scratch/prize",
      submit: e + "scratch/scratch/submit",
      log: e + "scratch/scratch/log",
      qrcode: e + "scratch/scratch/qrcode"
    }
  };
module.exports = r;